trigger:
  branches:
    include:
    - development
    - azure-pipeline*
  paths:
    include:
    - 'src/qa/*'

pr:
   branches:
    exclude:
    - '*'  
  
pool:
  vmImage: 'windows-2019'

variables:
  - name: buildConfiguration
    value: Release
  - name: url
    value: https://ashy-sky-0c1ce5203.azurestaticapps.net/

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/EatWell.QA.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  inputs:
    solution: '**/EatWell.QA.sln'
    configuration: '$(buildConfiguration)'

- task: FileTransform@1
  inputs:
    folderPath: $(System.DefaultWorkingDirectory)/src/qa/bin/$(buildConfiguration)
    fileType: 'xml'
    targetFiles: '**/packages.config'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/src/qa/bin/$(buildConfiguration)
    artifactName: WebApp

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\EatWell.QA.exe
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)/src/qa/bin/$(buildConfiguration)'
 
