trigger:
  paths:
    include: # Include!
    - 'src/ui/*'
  
pool:
  vmImage: 'windows-latest'

variables:
  - name: buildConfiguration
    value: 'Release'
  - name: stageName
    value: "First stage"

jobs:

- job: UI
  displayName: UI_Build 
  workspace:
    clean: all
  # variables:
  #   - group: Eat_Well_Variable_Group
  # steps:
  #   - template: src/devops/yaml/backend.yml