trigger:
  branches:
   include:
    - main
    - Release-CRUD
  paths:
    include:
    - 'src/ui/*'
  
variables:
  uiSource: "src/ui"

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: $(uiSource) 
      api_location: "api"
      output_location: "build"
    env:
      azure_static_web_apps_api_token: $(deployment_token)