trigger:
  paths:
    include:
    - 'src/ui/*'
  
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:    
      versionSpec: '14.x'
      checkLatest: true
     
  - task: CmdLine@2
    inputs:
      script: echo "Structure of work folder of this pipeline:"
        tree $(Agent.WorkFolder)\1 /f

        echo "Build.ArtifactStagingDirectory:" 

        echo "$(Build.ArtifactStagingDirectory)"

        echo "Build.BinariesDirectory:" 

        echo "$(Build.BinariesDirectory)"

        echo "Build.SourcesDirectory:"

        echo "$(Build.SourcesDirectory)"
        
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

 # - script: |
  #    npm install
   #   npm run build
    #displayName: 'npm install and build'