trigger:
  branches:
    include:
    - development
  paths:
    include:
    - 'src/api/*'

pr:
   branches:
    exclude:
    - '*'  
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  ProjectPath: 'src/api/EatWell.Web/EatWell.API.csproj'
  BuildConfiguration: 'Release'

steps:
 - task: DotNetCoreCLI@2
   displayName: 'Publish and zip'
   inputs:
    command: publish
    publishWebProjects: False
    projects: $(ProjectPath)
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

 - task: AzureWebApp@1
   displayName: 'Deploy Azure Web App'
   inputs:
    azureSubscription: 'azure_connection'
    appName: 'EW-API-TEST'
    appType: 'webApp'
    package: $(Build.ArtifactStagingDirectory)/**/*.zip